all methods for working with files on S3
tarkovskynik/Golang-ninja-project pull request #7
Opened 2022-10-07 13:26 UTC by o-sokol-o

2022-10-07 15:37 UTC, VadimGossip requested changes

2022-10-07 15:37 UTC, VadimGossip commented on internal/app/app.go
> +	cfg.File.MaxUploadSize = cfg.File.MaxUploadSize << 20 // 10 megabytes = 10 << 20
как я говорил, мне это не в файле конфиг совсем не нравится, @tarkovskynik а ты что думаешь?

2022-10-07 15:37 UTC, VadimGossip commented on internal/config/config.go
> +	if runtime.GOOS == "windows" {
Этого быть не должно приложение запускается в докере там проблем с окружениями среды нет.

2022-10-07 15:37 UTC, VadimGossip commented on internal/transport/rest/handler.go
> +type FilesServece interface {
Service

2022-10-07 15:37 UTC, VadimGossip commented on internal/transport/rest/middleware.go
> +	// headerParts := strings.Split(header, " ")
почему закоменчен кусок

2022-10-07 16:56 UTC, o-sokol-o commented on internal/app/app.go
> +	cfg.File.MaxUploadSize = cfg.File.MaxUploadSize << 20 // 10 megabytes = 10 << 20
Да, мне тоже интересно где этот код разместить, если данные из конфига требуют предварительной обработки.

2022-10-07 16:59 UTC, o-sokol-o commented on internal/config/config.go
> +	if runtime.GOOS == "windows" {
Думаю, что это можно оставить навсегда, ибо отладка под виндовс. А как мы знаем, написание приложения не может быть закончено навсегда.

2022-10-07 17:00 UTC, o-sokol-o commented on internal/transport/rest/handler.go
> +type FilesServece interface {
Провтыкал тут исправить ...

2022-10-07 17:01 UTC, o-sokol-o commented on internal/transport/rest/middleware.go
> +	// headerParts := strings.Split(header, " ")
Чтоб дать пищу для размышлений. Я раньше исправлял возврат на "Bearer "+токен. Были возражения.

2022-10-07 18:11 UTC, VadimGossip commented on internal/app/app.go
> +	cfg.File.MaxUploadSize = cfg.File.MaxUploadSize << 20 // 10 megabytes = 10 << 20
по мне обработать в конфиге

2022-10-07 18:13 UTC, VadimGossip approved these changes

2022-10-08 00:05 UTC, tarkovskynik approved these changes

2022-10-08 00:05 UTC, tarkovskynik commented on internal/app/app.go
> +	cfg.File.MaxUploadSize = cfg.File.MaxUploadSize << 20 // 10 megabytes = 10 << 20
в данной задаче пусть будет здесь

2022-10-08 00:05 UTC, tarkovskynik commented on internal/config/config.go
> +	if runtime.GOOS == "windows" {
это норм , пусть будет , можно держать спокойно под все операционки для теста проще чем постоянно билдить в докере

2022-10-08 00:06 UTC, merged